"""add geolocation to advert4

Revision ID: 0de0be6e42d8
Revises: 23a1e704c043
Create Date: 2026-03-06 08:38:38.210136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de0be6e42d8'
down_revision: Union[str, Sequence[str], None] = '23a1e704c043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'adverts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adverts', type_='foreignkey')
    op.drop_column('adverts', 'user_id')
    # ### end Alembic commands ###
