"""add geolocation to adverts

Revision ID: 23a1e704c043
Revises: 2dda00c57b75
Create Date: 2026-03-05 20:29:59.329936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a1e704c043'
down_revision: Union[str, Sequence[str], None] = '2dda00c57b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('adverts', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adverts', 'longitude')
    op.drop_column('adverts', 'latitude')
    # ### end Alembic commands ###
