"""rename column

Revision ID: 4010ca977444
Revises: f0a31b180048
Create Date: 2026-01-02 11:38:57.043457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4010ca977444'
down_revision: Union[str, Sequence[str], None] = 'f0a31b180048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('is_moderation', sa.Boolean(), nullable=True))
    op.drop_column('adverts', 'moderation')
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_email_verified')
    op.add_column('adverts', sa.Column('moderation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('adverts', 'is_moderation')
    # ### end Alembic commands ###
