"""Добавлено поле is_blacklisted 

Revision ID: 5f2edcc4d27a
Revises: ef6b1186bbee
Create Date: 2026-01-13 11:57:08.354751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2edcc4d27a'
down_revision: Union[str, Sequence[str], None] = 'ef6b1186bbee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blacklisted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blacklisted')
    # ### end Alembic commands ###
