"""Add columns

Revision ID: 86d484ec8ab3
Revises: 00597d29e042
Create Date: 2025-11-26 11:44:52.446882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d484ec8ab3'
down_revision: Union[str, Sequence[str], None] = '00597d29e042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_black_lists_id'), 'black_lists', ['id'], unique=False)
    op.add_column('redirections', sa.Column('redirection', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'agent_id')
    op.drop_column('redirections', 'redirection')
    op.drop_index(op.f('ix_black_lists_id'), table_name='black_lists')
    op.drop_table('black_lists')
    # ### end Alembic commands ###
