"""Fix Advert FK

Revision ID: 891d868aac22
Revises: 02e9fb0dffd2
Create Date: 2025-11-21 10:14:32.449597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891d868aac22'
down_revision: Union[str, Sequence[str], None] = '02e9fb0dffd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galleries_id'), 'galleries', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'AGENT', 'DEV', 'NOTARY', 'SALES_DEP', 'CLIENT', name='userrole'), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('housing_market', sa.Enum('SECONDARY', 'NEW_BUILD', 'COTTAGE', name='housing_market_enum'), nullable=True),
    sa.Column('build_status', sa.Enum('HANDED_OVER', 'PIT', name='build_status_enum'), nullable=True),
    sa.Column('district', sa.Enum('CENTER', 'KHORTYTSKY', 'KOSMICHESKY', name='district_enum'), nullable=True),
    sa.Column('microdistrict', sa.Enum('ONE', 'TWO', 'THREE', name='microdistrict_enum'), nullable=True),
    sa.Column('type_build', sa.Enum('APARTMENT_BUILDING', 'PRIVATE_HOUSE', name='build_type_enum'), nullable=True),
    sa.Column('payment', sa.Enum('CASH', 'MORTGAGE', 'INSTALLMENT', 'MATERNAL_CAPITAL', name='payment_enum'), nullable=True),
    sa.Column('finishing', sa.Enum('ROUGH', 'FINISHED', 'OPTION_3', name='finishing_enum'), nullable=True),
    sa.Column('utility_bills', sa.Enum('FIXED', 'BY_METER', name='utility_bills_enum'), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('price_from', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_to', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('area_from', sa.Float(), nullable=True),
    sa.Column('area_to', sa.Float(), nullable=True),
    sa.Column('distance_to_the_sea', sa.Integer(), nullable=True),
    sa.Column('ceiling_height', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filters_id'), 'filters', ['id'], unique=False)
    op.create_index(op.f('ix_filters_user_id'), 'filters', ['user_id'], unique=False)
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('information', sa.Text(), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gallery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('is_me', sa.Boolean(), nullable=True),
    sa.Column('is_me_agent', sa.Boolean(), nullable=True),
    sa.Column('is_agent', sa.Boolean(), nullable=True),
    sa.Column('turn_off', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('redirections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirections_id'), 'redirections', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('auto_renewal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('advantages_of_home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_parking', sa.Boolean(), nullable=True),
    sa.Column('is_sports_ground', sa.Boolean(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advantages_of_home_id'), 'advantages_of_home', ['id'], unique=False)
    op.create_table('adverts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('appointment', sa.Enum('APARTMENTS', 'FLAT', 'HOUSE', 'STUDIO', name='appointmentenum'), nullable=False),
    sa.Column('layout', sa.Enum('JOINT', 'SEPARATE', name='layoutenum'), nullable=True),
    sa.Column('state', sa.Enum('HANDED_OVER', 'PIT', name='stateenum'), nullable=True),
    sa.Column('heating', sa.Enum('CENTRALIZED', 'AUTONOMOUS', 'INDIVIDUAL', name='heatingenum'), nullable=True),
    sa.Column('payment', sa.Enum('USER', 'DEVELOPER', 'NOTARY', 'SALES_DEPARTMENT', name='paymentpartyenum'), nullable=True),
    sa.Column('communication', sa.Enum('USER', 'DEVELOPER', 'NOTARY', 'SALES_DEPARTMENT', name='communicationpartyenum'), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('kitchen_area', sa.Float(), nullable=True),
    sa.Column('is_balcony', sa.Boolean(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adverts_id'), 'adverts', ['id'], unique=False)
    op.create_table('corps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corps_id'), 'corps', ['id'], unique=False)
    op.create_index(op.f('ix_corps_name'), 'corps', ['name'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('infrastructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('APARTMENT', 'COTTAGE', 'HOUSE', name='buildingstatus', native_enum=False), nullable=True),
    sa.Column('type_build', sa.Enum('APARTMENT_BUILDING', 'PRIVATE_HOUSE', name='buildingtype', native_enum=False), nullable=True),
    sa.Column('class_at_home', sa.Enum('ELITE', 'BUDGET', name='homeclass', native_enum=False), nullable=True),
    sa.Column('construction_technology', sa.Enum('MONOLITH_EXPANDED_CLAY', 'BRICK', name='constructiontechnology', native_enum=False), nullable=True),
    sa.Column('territory', sa.Enum('CLOSED_GUARDED', 'CLOSED', 'OPEN_UNGUARDED', name='territorychoice', native_enum=False), nullable=True),
    sa.Column('gas', sa.Enum('YES', 'NO', name='gaschoice', native_enum=False), nullable=True),
    sa.Column('heating', sa.Enum('CENTRAL', 'INDIVIDUAL', name='heatingchoice', native_enum=False), nullable=True),
    sa.Column('sewerage', sa.Enum('INDIVIDUAL', 'CENTRAL', name='seweragechoice', native_enum=False), nullable=True),
    sa.Column('water_supply', sa.Enum('CENTRAL', 'INDIVIDUAL', name='watersupplychoice', native_enum=False), nullable=True),
    sa.Column('utility_bills', sa.Enum('FIXED', 'BY_METER', name='utilitybillschoice', native_enum=False), nullable=True),
    sa.Column('distance_to_sea', sa.Integer(), nullable=True),
    sa.Column('ceiling_height', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_id'), 'infrastructure', ['id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_table('registrations_and_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.Text(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('appointment', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrations_and_payments_id'), 'registrations_and_payments', ['id'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_frase', sa.Text(), nullable=True),
    sa.Column('is_color', sa.Boolean(), nullable=True),
    sa.Column('is_big_advert', sa.Boolean(), nullable=True),
    sa.Column('type_promotion', sa.Enum('UP', 'TURBO', name='typeenum'), nullable=True),
    sa.Column('advert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advert_id'], ['adverts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('corps_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corps_id'], ['corps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_index(op.f('ix_sections_name'), 'sections', ['name'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floors_id'), 'floors', ['id'], unique=False)
    op.create_index(op.f('ix_floors_name'), 'floors', ['name'], unique=False)
    op.create_table('risers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risers_id'), 'risers', ['id'], unique=False)
    op.create_index(op.f('ix_risers_name'), 'risers', ['name'], unique=False)
    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('price_metr', sa.DECIMAL(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('riser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['riser_id'], ['risers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flats_id'), 'flats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flats_id'), table_name='flats')
    op.drop_table('flats')
    op.drop_index(op.f('ix_risers_name'), table_name='risers')
    op.drop_index(op.f('ix_risers_id'), table_name='risers')
    op.drop_table('risers')
    op.drop_index(op.f('ix_floors_name'), table_name='floors')
    op.drop_index(op.f('ix_floors_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_sections_name'), table_name='sections')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_registrations_and_payments_id'), table_name='registrations_and_payments')
    op.drop_table('registrations_and_payments')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_infrastructure_id'), table_name='infrastructure')
    op.drop_table('infrastructure')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_corps_name'), table_name='corps')
    op.drop_index(op.f('ix_corps_id'), table_name='corps')
    op.drop_table('corps')
    op.drop_index(op.f('ix_adverts_id'), table_name='adverts')
    op.drop_table('adverts')
    op.drop_index(op.f('ix_advantages_of_home_id'), table_name='advantages_of_home')
    op.drop_table('advantages_of_home')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_redirections_id'), table_name='redirections')
    op.drop_table('redirections')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.drop_table('houses')
    op.drop_index(op.f('ix_filters_user_id'), table_name='filters')
    op.drop_index(op.f('ix_filters_id'), table_name='filters')
    op.drop_table('filters')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_galleries_id'), table_name='galleries')
    op.drop_table('galleries')
    # ### end Alembic commands ###
