"""Implemened message models 

Revision ID: 8c95cfcbb8b8
Revises: e0dabd7e93b9
Create Date: 2026-01-28 13:49:36.600345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c95cfcbb8b8'
down_revision: Union[str, Sequence[str], None] = 'e0dabd7e93b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
