"""Удалены поля главное изображение

Revision ID: 96d1e272a145
Revises: 5f2edcc4d27a
Create Date: 2026-01-20 19:15:47.735209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d1e272a145'
down_revision: Union[str, Sequence[str], None] = '5f2edcc4d27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gallery_images', 'is_main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery_images', sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
