"""Add house_id to galleries

Revision ID: 9c3222952a1d
Revises: 3b599b3688df
Create Date: 2025-11-21 22:10:56.441602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3222952a1d'
down_revision: Union[str, Sequence[str], None] = '3b599b3688df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galleries', sa.Column('house_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'galleries', 'houses', ['house_id'], ['id'])
    op.drop_constraint(op.f('houses_gallery_id_fkey'), 'houses', type_='foreignkey')
    op.drop_column('houses', 'gallery_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('gallery_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('houses_gallery_id_fkey'), 'houses', 'galleries', ['gallery_id'], ['id'])
    op.drop_constraint(None, 'galleries', type_='foreignkey')
    op.drop_column('galleries', 'house_id')
    # ### end Alembic commands ###
