"""Add galleries and gallery_images, add gallery_id to houses and adverts

Revision ID: a36a9257688a
Revises: 9063b20414c0
Create Date: 2025-12-26 11:00:23.473290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36a9257688a'
down_revision: Union[str, Sequence[str], None] = '9063b20414c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('adverts', sa.Column('gallery_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'adverts', 'galleries', ['gallery_id'], ['id'])
    op.drop_index(op.f('ix_gallery_house_position'), table_name='galleries')
    op.drop_constraint(op.f('galleries_house_id_fkey'), 'galleries', type_='foreignkey')
    op.drop_column('galleries', 'image')
    op.drop_column('galleries', 'is_main')
    op.drop_column('galleries', 'position')
    op.drop_column('galleries', 'house_id')
    op.add_column('houses', sa.Column('gallery_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'houses', 'galleries', ['gallery_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_column('houses', 'gallery_id')
    op.add_column('galleries', sa.Column('house_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('galleries', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('galleries', sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('galleries', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('galleries_house_id_fkey'), 'galleries', 'houses', ['house_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_gallery_house_position'), 'galleries', ['house_id', 'position'], unique=False)
    op.drop_constraint(None, 'adverts', type_='foreignkey')
    op.drop_column('adverts', 'gallery_id')
    op.drop_table('gallery_images')
    # ### end Alembic commands ###
