"""rename column advert and add column

Revision ID: dc31de46e298
Revises: 4010ca977444
Create Date: 2026-01-02 13:10:39.591076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc31de46e298'
down_revision: Union[str, Sequence[str], None] = '4010ca977444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.drop_column('adverts', 'is_moderation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('is_moderation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('adverts', 'is_approved')
    # ### end Alembic commands ###
