"""

Revision ID: e0dabd7e93b9
Revises: 96d1e272a145
Create Date: 2026-01-28 11:12:12.122499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0dabd7e93b9'
down_revision: Union[str, Sequence[str], None] = '96d1e272a145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('promotions', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'end_date')
    op.drop_column('promotions', 'start_date')
    # ### end Alembic commands ###
