"""rename column advert and add colum3

Revision ID: ef6b1186bbee
Revises: ce3408e2e42b
Create Date: 2026-01-02 13:16:18.047263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6b1186bbee'
down_revision: Union[str, Sequence[str], None] = 'ce3408e2e42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adverts', 'is_active')
    # ### end Alembic commands ###
