"""Add column for user- Email_verifaied and model advert add column moderation

Revision ID: f0a31b180048
Revises: 0b718f350759
Create Date: 2026-01-02 10:50:40.179969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a31b180048'
down_revision: Union[str, Sequence[str], None] = '0b718f350759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
